##
# Use this file as template.
#
# Save
#
# Sync types are:
#    - default For all hosts the most secure sync method.
#    - nfs (recommended for Linux and Mac)
#    - smb (recommended for Windows)
vagrantfile:
    vm:
        synced_folder:
            thunder:
                source: '/Path/To/The/Current/Project'
                target: /var/www/project.dev
                sync_type: nfs
                smb:
                    smb_username: ''
                    smb_password: ''
                    mount_options:
                        dir_mode: 0775
                        file_mode: 0664
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
        usable_port_range:
            start: 10200
            stop: 10500
