##
# Use this file as template.
#
# Save
#
# Sync types are:
#    - default For all hosts the most secure sync method.
#    - nfs (recommended for Linux and Mac)
#    - smb (recommended for Windows)
vagrantfile:
    vm:
        provider:
            local:
                machines:
                    vflm_ngtk2d5a3shv:
                        id: projectid
                        network:
                            private_network: 192.168.56.88
                            forwarded_port:
                                vflmnfp_4zbfjfn4jegc:
                                    host: '9289'
                                    guest: '22'
                                vflnp_rvqshw7nr098:
                                    host: '35729'
                                    guest: '35729'
                        hostname: local.projectid
                        memory: '2046'
                        cpus: '2'
        synced_folder:
            thunder:
                source: /Path/To/The/Current/Project
                target: /var/www/project.dev
                sync_type: nfs
                smb:
                    smb_username: ''
                    smb_password: ''
                    mount_options:
                        dir_mode: 0775
                        file_mode: 0664
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
        usable_port_range:
            start: 10200
            stop: 10500
